#DB 연동
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:44000/ddang_kong
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


ssh:
  host: ${url}
  sshPort: 22
  user: ${user}
  privatekey: ${privatekey}
  database_port: 3307