#DB 연동
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ddang_kong
    username: admin
    password: kongadmin2025

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


ssh:
  host: kongback.kro.kr
  sshPort: 22
  user: ubuntu
  privatekey: src/main/resources/dbssh/DDANG_KONG-KEY.pem
  database_port: 3307
