#DB 연동
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:44000/ddang_kong
    username: admin
    password: kongadmin2025

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  websocket:
    message-size-limit: 5242880

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


ssh:
  host: kongback.kro.kr
  sshPort: 22
  user: ubuntu
  privatekey: src/main/resources/dbssh/DDANG_KONG-KEY.pem
  database_port: 3307

app:
  storage:
    local:
      base-dir: /home/ubuntu/app/videos
  media:
    public-base-url: http://kongback.kro.kr/media

server:
  port: 8080
  tomcat:
    max-http-response-header-size: 32KB
